### ISSUE TITLE
Develop branch, Error on docker run ImportError: No module named gi

### ISSUE THREAD

**Issue by heralight** [akatrevorjay/docker-mopidy-extras#1]
Hi!

I try to run it, and I get  error bellow, do you have an idea howto fix that please ?
This error doesn't append with latest...

Thank you,

Alexandre

$ docker run --rm trevorj/mopidy-extras:develop
userdel: user 'app' does not exist
mkdir: created directory '/app/.config/mopidy'
changed ownership of '/app' from root to app
changed ownership of '/app/.config' from root to app
changed ownership of '/app/.config/mopidy' from root to app
changed ownership of '/app/.local/share' from root to app
changed ownership of '/app/.local/share/mopidy' from root to app
'/app/image/mopidy.conf' -> '/app/.config/mopidy/mopidy.conf'
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 7, in <module>

ERROR: A GObject Python package was not found.

Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.

Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

from mopidy.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: F401
  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/gi.py", line 8, in <module>
    import gi
ImportError: No module named gi

**Comment by akatrevorjay** [comment]
Hi!

Ah, it must require `python-gi`, I'll add that in now!

**Comment by akatrevorjay** [comment]
The dependencies must have changed, as this worked without it before.

**Comment by akatrevorjay** [comment]
I verified the latest build starts just fine for me, if this still happens for you let me know, but all looks good from here now!

Thanks for the report~~!

```
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, AudioAddictBackend
INFO     Creating dir /app/.local/share/mopidy/m3u
INFO     AudioAddict: premium streams not available on your account
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend, NotifierFrontend, SpotmopFrontend, QueueManagerFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Creating dir /app/.local/share/mopidy/local-images
INFO     Starting Spotmop 2.10.1
INFO     Starting GLib mainloop
INFO     Pusher server running at [0.0.0.0]:6681
